version: '3.8'

services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - model
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
