version: '3.8'

services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
